#!/bin/bash

set -e

export PHP_VERSION=5.5.14

cd /var/cache

#if [ ! -f /var/cache/php-${PHP_VERSION}.tar.bz2 ]; then
#  wget -q -o php-${PHP_VERSION}.tar.bz2 http://www.php.net/get/php-${PHP_VERSION}.tar.bz2/from/this/mirror
#fi
tar jvxf php-${PHP_VERSION}.tar.bz2

pushd /var/cache/php-${PHP_VERSION}
./configure --prefix=/app/php --enable-fastcgi --with-mysql=mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd
make
make install
popd

cd /app
tar cjvf php-${PHP_VERSION}.tar.bz2 php
mkdir -p /var/cache/out
cp php-${PHP_VERSION}.tar.bz2 /var/cache/out


